### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [andyiac/githot#1]
Would you consider attaching the `.apk` with each of the `releases/`, so people without access to _Google Play Store_ can grab it? I know you've linked a download to some "Fir" site, but that's not the same (another site one has to trust that it doesn't e.g. manipulate the file). Having it right here would be much preferred :)

**Comment by andyiac** [comment]
@IzzySoft Great idea, and thanks for your suggestion, now you can find `.apk` file in `releases/` ;-D

**Comment by IzzySoft** [comment]
Great – thanks a lot! You might wish to update your main [README.md](https://github.com/andyiac/githot/blob/master/README.md) with the download link then :)

PS: As long as you continue to place new releases under `releases/`, those will be automatically available via [my repo](https://android.izzysoft.de/repo) using the F-Droid client, so people using that will automatically be notified and have an easy way to update – even if they, like me, don't use the Google apps.
